/// <reference path="../pb_data/types.d.ts" />

// syncLog — append-only record of every synchronisation in or out of this instance.
//
// `out`: an export was served (export-assignment, export-events). `in`: something was taken in
// (permanent-numbers import / materialise, or the consumer's export-ack — the cash-desk side
// saying "this checksum is now the market's file"). A pull alone is not a sync; the ack is what
// makes "last sync" mean something.
//
// Superuser-only on all five rules; a future admin UI reads the latest entry per kind through
// /api/seller-number/sync-status. `summary` carries counters and case classes only — never a
// name, email or row.
migrate(
  (app) => {
    const collection = new Collection({
      type: 'base',
      name: 'syncLog',
      listRule: null,
      viewRule: null,
      createRule: null,
      updateRule: null,
      deleteRule: null,
      fields: [
        {
          autogeneratePattern: '[a-z0-9]{15}',
          hidden: false,
          id: 'text3208210256',
          max: 15,
          min: 15,
          name: 'id',
          pattern: '^[a-z0-9]+$',
          presentable: false,
          primaryKey: true,
          required: true,
          system: true,
          type: 'text',
        },
        {
          hidden: false,
          id: 'select_syncLog_direction',
          maxSelect: 1,
          name: 'direction',
          presentable: true,
          required: true,
          system: false,
          type: 'select',
          values: ['out', 'in'],
        },
        {
          hidden: false,
          id: 'select_syncLog_kind',
          maxSelect: 1,
          name: 'kind',
          presentable: true,
          required: true,
          system: false,
          type: 'select',
          values: [
            'export-assignment',
            'export-events',
            'export-ack',
            'permanent-numbers-import',
            'permanent-numbers-materialise',
          ],
        },
        {
          cascadeDelete: false,
          collectionId: 'pbc_1687431684',
          hidden: false,
          id: 'relation_syncLog_event',
          maxSelect: 1,
          minSelect: 0,
          name: 'event',
          presentable: true,
          required: false,
          system: false,
          type: 'relation',
        },
        {
          autogeneratePattern: '',
          hidden: false,
          id: 'text_syncLog_client',
          max: 200,
          min: 0,
          name: 'client',
          pattern: '',
          presentable: false,
          primaryKey: false,
          required: false,
          system: false,
          type: 'text',
        },
        {
          autogeneratePattern: '',
          hidden: false,
          id: 'text_syncLog_mode',
          max: 10,
          min: 0,
          name: 'mode',
          pattern: '',
          presentable: false,
          primaryKey: false,
          required: false,
          system: false,
          type: 'text',
        },
        {
          autogeneratePattern: '',
          hidden: false,
          id: 'text_syncLog_checksum',
          max: 64,
          min: 0,
          name: 'checksum',
          pattern: '^[a-f0-9]{64}$',
          presentable: false,
          primaryKey: false,
          required: false,
          system: false,
          type: 'text',
        },
        {
          hidden: false,
          id: 'number_syncLog_rowCount',
          max: null,
          min: 0,
          name: 'rowCount',
          onlyInt: true,
          presentable: false,
          required: false,
          system: false,
          type: 'number',
        },
        {
          hidden: false,
          id: 'bool_syncLog_dryRun',
          name: 'dryRun',
          presentable: false,
          required: false,
          system: false,
          type: 'bool',
        },
        {
          hidden: false,
          id: 'select_syncLog_status',
          maxSelect: 1,
          name: 'status',
          presentable: true,
          required: true,
          system: false,
          type: 'select',
          values: ['ok', 'error'],
        },
        {
          hidden: false,
          id: 'json_syncLog_summary',
          maxSize: 20000,
          name: 'summary',
          presentable: false,
          required: false,
          system: false,
          type: 'json',
        },
        {
          autogeneratePattern: '',
          hidden: false,
          id: 'text_syncLog_ip',
          max: 100,
          min: 0,
          name: 'ipAddress',
          pattern: '',
          presentable: false,
          primaryKey: false,
          required: false,
          system: false,
          type: 'text',
        },
        {
          hidden: false,
          id: 'date_syncLog_startedAt',
          max: '',
          min: '',
          name: 'startedAt',
          presentable: false,
          required: false,
          system: false,
          type: 'date',
        },
        {
          hidden: false,
          id: 'date_syncLog_finishedAt',
          max: '',
          min: '',
          name: 'finishedAt',
          presentable: false,
          required: false,
          system: false,
          type: 'date',
        },
        {
          hidden: false,
          id: 'autodate_syncLog_created',
          name: 'created',
          onCreate: true,
          onUpdate: false,
          presentable: false,
          system: false,
          type: 'autodate',
        },
      ],
      indexes: [
        // sync-status asks "latest per kind (and event)".
        'CREATE INDEX `idx_syncLog_kind_finished` ON `syncLog` (`kind`, `finishedAt`)',
        'CREATE INDEX `idx_syncLog_event` ON `syncLog` (`event`)',
      ],
    })

    return app.save(collection)
  },
  (app) => {
    const collection = app.findCollectionByNameOrId('syncLog')
    return app.delete(collection)
  }
)
