/// <reference path="../pb_data/types.d.ts" />

// marketStats — one row per (event category, market): the baselines a Dauernummer is measured
// against. Mean and median of items sold and revenue over all sellers of that market, and the
// same four over the sellers who held a Dauernummer. Numbers only; kept for every market (a
// handful of rows a year), so a trend across markets stays readable.
//
// Pushed by the cash-desk side together with permanentNumberMarkets (KKM-legacy plan §1.10).
// Superuser-only rules.
migrate(
  (app) => {
    const collection = new Collection({
      type: 'base',
      name: 'marketStats',
      listRule: null,
      viewRule: null,
      createRule: null,
      updateRule: null,
      deleteRule: null,
      fields: [
        {
          autogeneratePattern: '[a-z0-9]{15}',
          hidden: false,
          id: 'text3208210256',
          max: 15,
          min: 15,
          name: 'id',
          pattern: '^[a-z0-9]+$',
          presentable: false,
          primaryKey: true,
          required: true,
          system: true,
          type: 'text',
        },
        {
          cascadeDelete: false,
          collectionId: 'pbc_3505075978',
          hidden: false,
          id: 'relation_ms_category',
          maxSelect: 1,
          minSelect: 0,
          name: 'eventCategory',
          presentable: true,
          required: true,
          system: false,
          type: 'relation',
        },
        {
          autogeneratePattern: '',
          hidden: false,
          id: 'text_ms_market',
          max: 8,
          min: 8,
          name: 'market',
          pattern: '^[0-9]{4}-(Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)$',
          presentable: true,
          primaryKey: false,
          required: true,
          system: false,
          type: 'text',
        },
        {
          cascadeDelete: false,
          collectionId: 'pbc_1687431684',
          hidden: false,
          id: 'relation_ms_event',
          maxSelect: 1,
          minSelect: 0,
          name: 'event',
          presentable: false,
          required: false,
          system: false,
          type: 'relation',
        },
        {
          hidden: false,
          id: 'number_ms_sellers',
          max: null,
          min: 0,
          name: 'sellers',
          onlyInt: true,
          presentable: false,
          required: false,
          system: false,
          type: 'number',
        },
        {
          hidden: false,
          id: 'number_ms_itemsMean',
          max: null,
          min: 0,
          name: 'itemsMean',
          onlyInt: false,
          presentable: false,
          required: false,
          system: false,
          type: 'number',
        },
        {
          hidden: false,
          id: 'number_ms_itemsMedian',
          max: null,
          min: 0,
          name: 'itemsMedian',
          onlyInt: false,
          presentable: false,
          required: false,
          system: false,
          type: 'number',
        },
        {
          hidden: false,
          id: 'number_ms_revenueCentsMean',
          max: null,
          min: 0,
          name: 'revenueCentsMean',
          onlyInt: true,
          presentable: false,
          required: false,
          system: false,
          type: 'number',
        },
        {
          hidden: false,
          id: 'number_ms_revenueCentsMedian',
          max: null,
          min: 0,
          name: 'revenueCentsMedian',
          onlyInt: true,
          presentable: false,
          required: false,
          system: false,
          type: 'number',
        },
        {
          hidden: false,
          id: 'number_ms_pnSellers',
          max: null,
          min: 0,
          name: 'permanentSellers',
          onlyInt: true,
          presentable: false,
          required: false,
          system: false,
          type: 'number',
        },
        {
          hidden: false,
          id: 'number_ms_pnItemsMean',
          max: null,
          min: 0,
          name: 'permanentItemsMean',
          onlyInt: false,
          presentable: false,
          required: false,
          system: false,
          type: 'number',
        },
        {
          hidden: false,
          id: 'number_ms_pnItemsMedian',
          max: null,
          min: 0,
          name: 'permanentItemsMedian',
          onlyInt: false,
          presentable: false,
          required: false,
          system: false,
          type: 'number',
        },
        {
          hidden: false,
          id: 'number_ms_pnRevenueCentsMean',
          max: null,
          min: 0,
          name: 'permanentRevenueCentsMean',
          onlyInt: true,
          presentable: false,
          required: false,
          system: false,
          type: 'number',
        },
        {
          hidden: false,
          id: 'number_ms_pnRevenueCentsMedian',
          max: null,
          min: 0,
          name: 'permanentRevenueCentsMedian',
          onlyInt: true,
          presentable: false,
          required: false,
          system: false,
          type: 'number',
        },
        {
          hidden: false,
          id: 'autodate_ms_created',
          name: 'created',
          onCreate: true,
          onUpdate: false,
          presentable: false,
          system: false,
          type: 'autodate',
        },
        {
          hidden: false,
          id: 'autodate_ms_updated',
          name: 'updated',
          onCreate: true,
          onUpdate: true,
          presentable: false,
          system: false,
          type: 'autodate',
        },
      ],
      indexes: [
        'CREATE UNIQUE INDEX `idx_ms_category_market` ON `marketStats` (`eventCategory`, `market`)',
      ],
    })

    return app.save(collection)
  },
  (app) => {
    const collection = app.findCollectionByNameOrId('marketStats')
    return app.delete(collection)
  }
)
