/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as NoReservationImport } from './routes/no-reservation'
import { Route as ConditionsImport } from './routes/conditions'
import { Route as IndexImport } from './routes/index'
import { Route as VariationVariationIdSellerNumberSellerNumberConditionsImport } from './routes/variation.$variationId.sellerNumber.$sellerNumber/conditions'

// Create/Update Routes

const NoReservationRoute = NoReservationImport.update({
  id: '/no-reservation',
  path: '/no-reservation',
  getParentRoute: () => rootRoute,
} as any)

const ConditionsRoute = ConditionsImport.update({
  id: '/conditions',
  path: '/conditions',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const VariationVariationIdSellerNumberSellerNumberConditionsRoute =
  VariationVariationIdSellerNumberSellerNumberConditionsImport.update({
    id: '/variation/$variationId/sellerNumber/$sellerNumber/conditions',
    path: '/variation/$variationId/sellerNumber/$sellerNumber/conditions',
    getParentRoute: () => rootRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/conditions': {
      id: '/conditions'
      path: '/conditions'
      fullPath: '/conditions'
      preLoaderRoute: typeof ConditionsImport
      parentRoute: typeof rootRoute
    }
    '/no-reservation': {
      id: '/no-reservation'
      path: '/no-reservation'
      fullPath: '/no-reservation'
      preLoaderRoute: typeof NoReservationImport
      parentRoute: typeof rootRoute
    }
    '/variation/$variationId/sellerNumber/$sellerNumber/conditions': {
      id: '/variation/$variationId/sellerNumber/$sellerNumber/conditions'
      path: '/variation/$variationId/sellerNumber/$sellerNumber/conditions'
      fullPath: '/variation/$variationId/sellerNumber/$sellerNumber/conditions'
      preLoaderRoute: typeof VariationVariationIdSellerNumberSellerNumberConditionsImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/conditions': typeof ConditionsRoute
  '/no-reservation': typeof NoReservationRoute
  '/variation/$variationId/sellerNumber/$sellerNumber/conditions': typeof VariationVariationIdSellerNumberSellerNumberConditionsRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/conditions': typeof ConditionsRoute
  '/no-reservation': typeof NoReservationRoute
  '/variation/$variationId/sellerNumber/$sellerNumber/conditions': typeof VariationVariationIdSellerNumberSellerNumberConditionsRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/conditions': typeof ConditionsRoute
  '/no-reservation': typeof NoReservationRoute
  '/variation/$variationId/sellerNumber/$sellerNumber/conditions': typeof VariationVariationIdSellerNumberSellerNumberConditionsRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/conditions'
    | '/no-reservation'
    | '/variation/$variationId/sellerNumber/$sellerNumber/conditions'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/conditions'
    | '/no-reservation'
    | '/variation/$variationId/sellerNumber/$sellerNumber/conditions'
  id:
    | '__root__'
    | '/'
    | '/conditions'
    | '/no-reservation'
    | '/variation/$variationId/sellerNumber/$sellerNumber/conditions'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConditionsRoute: typeof ConditionsRoute
  NoReservationRoute: typeof NoReservationRoute
  VariationVariationIdSellerNumberSellerNumberConditionsRoute: typeof VariationVariationIdSellerNumberSellerNumberConditionsRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConditionsRoute: ConditionsRoute,
  NoReservationRoute: NoReservationRoute,
  VariationVariationIdSellerNumberSellerNumberConditionsRoute:
    VariationVariationIdSellerNumberSellerNumberConditionsRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/conditions",
        "/no-reservation",
        "/variation/$variationId/sellerNumber/$sellerNumber/conditions"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/conditions": {
      "filePath": "conditions.tsx"
    },
    "/no-reservation": {
      "filePath": "no-reservation.tsx"
    },
    "/variation/$variationId/sellerNumber/$sellerNumber/conditions": {
      "filePath": "variation.$variationId.sellerNumber.$sellerNumber/conditions.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
